// <auto-generated />
using System;
using System.Collections.Generic;
using DataManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("expegraph")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataManagement.Models.Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("batch_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BatchId"));

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("batch_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("FabricationDate")
                        .HasColumnType("date")
                        .HasColumnName("fabrication_date");

                    b.Property<int?>("LabId")
                        .HasColumnType("integer")
                        .HasColumnName("lab_id");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("Treatment")
                        .HasColumnType("text")
                        .HasColumnName("treatment");

                    b.HasKey("BatchId");

                    b.HasIndex("BatchName")
                        .IsUnique();

                    b.HasIndex("LabId");

                    b.HasIndex("ProjectId");

                    b.ToTable("batches", "expegraph");
                });

            modelBuilder.Entity("DataManagement.Models.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeviceId"));

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("device_name");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("device_type");

                    b.Property<int>("SampleId")
                        .HasColumnType("integer")
                        .HasColumnName("sample_id");

                    b.HasKey("DeviceId");

                    b.HasIndex("SampleId");

                    b.ToTable("devices", "expegraph");
                });

            modelBuilder.Entity("DataManagement.Models.DeviceParameter", b =>
                {
                    b.Property<int>("DeviceParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("device_parameter_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeviceParameterId"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("DeviceParameterId");

                    b.HasIndex("DeviceId", "Key")
                        .IsUnique();

                    b.ToTable("device_parameters", "expegraph");
                });

            modelBuilder.Entity("DataManagement.Models.Diode", b =>
                {
                    b.Property<int>("DiodeId")
                        .HasColumnType("integer")
                        .HasColumnName("diode_id");

                    b.Property<float?>("AnodeLengthUm")
                        .HasColumnType("real")
                        .HasColumnName("anode_length_um");

                    b.Property<float?>("AnodeRadiusUm")
                        .HasColumnType("real")
                        .HasColumnName("anode_radius_um");

                    b.Property<float?>("AnodeWidthUm")
                        .HasColumnType("real")
                        .HasColumnName("anode_width_um");

                    b.Property<float?>("BarrierHeightEv")
                        .HasColumnType("real")
                        .HasColumnName("barrier_height_ev");

                    b.Property<float?>("BreakdownVoltageV")
                        .HasColumnType("real")
                        .HasColumnName("breakdown_voltage_v");

                    b.Property<float?>("BuiltInPotentialV")
                        .HasColumnType("real")
                        .HasColumnName("built_in_potential_v");

                    b.Property<double?>("CarrierConcentration")
                        .HasColumnType("double precision")
                        .HasColumnName("carrier_concentration");

                    b.Property<float?>("ChamferRadiusUm")
                        .HasColumnType("real")
                        .HasColumnName("chamfer_radius_um");

                    b.Property<Dictionary<string, object>>("GeometryProperties")
                        .HasColumnType("jsonb")
                        .HasColumnName("geometry_properties");

                    b.Property<string>("GeometryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("geometry_type");

                    b.Property<float?>("IdealityFactor")
                        .HasColumnType("real")
                        .HasColumnName("ideality_factor");

                    b.Property<float?>("MaxCurrentA")
                        .HasColumnType("real")
                        .HasColumnName("max_current_a");

                    b.Property<float?>("RecRatio")
                        .HasColumnType("real")
                        .HasColumnName("rec_ratio");

                    b.Property<float?>("VoltageAtMaxCurrentV")
                        .HasColumnType("real")
                        .HasColumnName("voltage_at_max_current_v");

                    b.HasKey("DiodeId");

                    b.ToTable("diodes", "expegraph", t =>
                        {
                            t.HasCheckConstraint("CK_diodes_geometry_type", "geometry_type IN ('rectangular', 'circular', 'other')");
                        });
                });

            modelBuilder.Entity("DataManagement.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("equipment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EquipmentId"));

                    b.Property<DateOnly?>("CalibrationDue")
                        .HasColumnType("date")
                        .HasColumnName("calibration_due");

                    b.Property<string>("ConnectingStr")
                        .HasColumnType("text")
                        .HasColumnName("connecting_str");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("equipment_name");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<short?>("PurchaseYear")
                        .HasColumnType("smallint")
                        .HasColumnName("purchase_year");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.HasKey("EquipmentId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("equipment", "expegraph");
                });

            modelBuilder.Entity("DataManagement.Models.Lab", b =>
                {
                    b.Property<int>("LabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("lab_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LabId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("LabLeaderId")
                        .HasColumnType("integer")
                        .HasColumnName("lab_leader_id");

                    b.Property<string>("LabName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lab_name");

                    b.HasKey("LabId");

                    b.HasIndex("LabLeaderId")
                        .IsUnique();

                    b.HasIndex("LabName")
                        .IsUnique();

                    b.ToTable("labs", "expegraph");
                });

            modelBuilder.Entity("DataManagement.Models.LabEquipment", b =>
                {
                    b.Property<int>("LabId")
                        .HasColumnType("integer")
                        .HasColumnName("lab_id");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_id");

                    b.HasKey("LabId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("labs_equipment", "expegraph");
                });

            modelBuilder.Entity("DataManagement.Models.LabProject", b =>
                {
                    b.Property<int>("LabId")
                        .HasColumnType("integer")
                        .HasColumnName("lab_id");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.HasKey("LabId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("labs_projects", "expegraph");
                });

            modelBuilder.Entity("DataManagement.Models.Measurement", b =>
                {
                    b.Property<int>("MeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("measurement_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MeasurementId"));

                    b.Property<string>("DataFilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_file_path");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_id");

                    b.Property<float?>("HumidityPercent")
                        .HasColumnType("real")
                        .HasColumnName("humidity_percent");

                    b.Property<DateTime>("MeasuredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("MeasurementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("measurement_type");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("SampleId")
                        .HasColumnType("integer")
                        .HasColumnName("sample_id");

                    b.Property<float?>("TemperatureK")
                        .HasColumnType("real")
                        .HasColumnName("temperature_k");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("MeasurementId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("MeasuredAt");

                    b.HasIndex("SampleId");

                    b.HasIndex("UserId");

                    b.ToTable("measurements", "expegraph", t =>
                        {
                            t.HasCheckConstraint("measurements_target_check", "(device_id IS NOT NULL AND sample_id IS NULL) OR (device_id IS NULL AND sample_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("DataManagement.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission_name");

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionName")
                        .IsUnique();

                    b.ToTable("permissions", "expegraph");
                });

            modelBuilder.Entity("DataManagement.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Funding")
                        .HasColumnType("text")
                        .HasColumnName("funding");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_name");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("ProjectId");

                    b.ToTable("projects", "expegraph");
                });

            modelBuilder.Entity("DataManagement.Models.Resistor", b =>
                {
                    b.Property<int>("ResistorId")
                        .HasColumnType("integer")
                        .HasColumnName("resistor_id");

                    b.Property<float?>("GapUm")
                        .HasColumnType("real")
                        .HasColumnName("gap_um");

                    b.Property<Dictionary<string, object>>("GeometryProperties")
                        .HasColumnType("jsonb")
                        .HasColumnName("geometry_properties");

                    b.Property<string>("GeometryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("geometry_type");

                    b.Property<float?>("InnerRadiusUm")
                        .HasColumnType("real")
                        .HasColumnName("inner_radius_um");

                    b.Property<float?>("OuterRadiusUm")
                        .HasColumnType("real")
                        .HasColumnName("outer_radius_um");

                    b.Property<float?>("ResistanceOhm")
                        .HasColumnType("real")
                        .HasColumnName("resistance_ohm");

                    b.Property<int?>("TlmId")
                        .HasColumnType("integer")
                        .HasColumnName("tlm_id");

                    b.Property<float?>("WidthUm")
                        .HasColumnType("real")
                        .HasColumnName("width_um");

                    b.HasKey("ResistorId");

                    b.HasIndex("TlmId");

                    b.ToTable("resistors", "expegraph", t =>
                        {
                            t.HasCheckConstraint("CK_resistors_geometry_type", "geometry_type IN ('rectangular', 'circular', 'other')");
                        });
                });

            modelBuilder.Entity("DataManagement.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("roles", "expegraph");
                });

            modelBuilder.Entity("DataManagement.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("roles_permissions", "expegraph");
                });

            modelBuilder.Entity("DataManagement.Models.Sample", b =>
                {
                    b.Property<int>("SampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sample_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SampleId"));

                    b.Property<int?>("BatchId")
                        .HasColumnType("integer")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Dictionary<string, object>>("Properties")
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<string>("SampleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sample_name");

                    b.Property<string>("Treatment")
                        .HasColumnType("text")
                        .HasColumnName("treatment");

                    b.HasKey("SampleId");

                    b.HasIndex("BatchId");

                    b.ToTable("samples", "expegraph");
                });

            modelBuilder.Entity("DataManagement.Models.Tlm", b =>
                {
                    b.Property<int>("TlmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tlm_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TlmId"));

                    b.Property<float?>("ContactResistanceOhm")
                        .HasColumnType("real")
                        .HasColumnName("contact_resistance_ohm");

                    b.Property<string>("GeometryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("geometry_type");

                    b.Property<float?>("SheetResistanceOhmSq")
                        .HasColumnType("real")
                        .HasColumnName("sheet_resistance_ohm_sq");

                    b.Property<float?>("TransferLengthCm")
                        .HasColumnType("real")
                        .HasColumnName("transfer_length_cm");

                    b.HasKey("TlmId");

                    b.ToTable("tlms", "expegraph", t =>
                        {
                            t.HasCheckConstraint("CK_tlms_geometry_type", "geometry_type IN ('rectangular', 'circular', 'other')");
                        });
                });

            modelBuilder.Entity("DataManagement.Models.Transistor", b =>
                {
                    b.Property<int>("TransistorId")
                        .HasColumnType("integer")
                        .HasColumnName("transistor_id");

                    b.Property<float?>("CoverageSectorDegree")
                        .HasColumnType("real")
                        .HasColumnName("coverage_sector_degree");

                    b.Property<float?>("DgGapUm")
                        .HasColumnType("real")
                        .HasColumnName("dg_gap_um");

                    b.Property<float?>("GateInnerRadiusUm")
                        .HasColumnType("real")
                        .HasColumnName("gate_inner_radius_um");

                    b.Property<float?>("GateLengthUm")
                        .HasColumnType("real")
                        .HasColumnName("gate_length_um");

                    b.Property<float?>("GateOuterRadiusUm")
                        .HasColumnType("real")
                        .HasColumnName("gate_outer_radius_um");

                    b.Property<float?>("GateWidthUm")
                        .HasColumnType("real")
                        .HasColumnName("gate_width_um");

                    b.Property<Dictionary<string, object>>("GeometryProperties")
                        .HasColumnType("jsonb")
                        .HasColumnName("geometry_properties");

                    b.Property<string>("GeometryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("geometry_type");

                    b.Property<float?>("MobilityCm2Vs")
                        .HasColumnType("real")
                        .HasColumnName("mobility_cm2_vs");

                    b.Property<float?>("OnOffRatio")
                        .HasColumnType("real")
                        .HasColumnName("on_off_ratio");

                    b.Property<float?>("SgGapUm")
                        .HasColumnType("real")
                        .HasColumnName("sg_gap_um");

                    b.Property<float?>("SubthresholdSwingMvDec")
                        .HasColumnType("real")
                        .HasColumnName("subthreshold_swing_mv_dec");

                    b.Property<float?>("ThresholdVoltageV")
                        .HasColumnType("real")
                        .HasColumnName("threshold_voltage_v");

                    b.HasKey("TransistorId");

                    b.ToTable("transistors", "expegraph", t =>
                        {
                            t.HasCheckConstraint("CK_transistors_geometry_type", "geometry_type IN ('rectangular', 'circular', 'other')");
                        });
                });

            modelBuilder.Entity("DataManagement.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("TRUE");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", "expegraph");
                });

            modelBuilder.Entity("DataManagement.Models.UserLab", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("LabId")
                        .HasColumnType("integer")
                        .HasColumnName("lab_id");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("member")
                        .HasColumnName("role");

                    b.HasKey("UserId", "LabId");

                    b.HasIndex("LabId");

                    b.ToTable("users_labs", "expegraph", t =>
                        {
                            t.HasCheckConstraint("CK_users_labs_role", "role IN ('leader', 'deputy_leader', 'member', 'student')");
                        });
                });

            modelBuilder.Entity("DataManagement.Models.UserProject", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.HasKey("UserId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("users_projects", "expegraph");
                });

            modelBuilder.Entity("DataManagement.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateOnly?>("RoleEndDate")
                        .HasColumnType("date")
                        .HasColumnName("role_end_date");

                    b.Property<DateOnly?>("RoleStartDate")
                        .HasColumnType("date")
                        .HasColumnName("role_start_date");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("users_roles", "expegraph");
                });

            modelBuilder.Entity("DataManagement.Models.Batch", b =>
                {
                    b.HasOne("DataManagement.Models.Lab", null)
                        .WithMany()
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataManagement.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DataManagement.Models.Device", b =>
                {
                    b.HasOne("DataManagement.Models.Sample", "Sample")
                        .WithMany("Devices")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("DataManagement.Models.DeviceParameter", b =>
                {
                    b.HasOne("DataManagement.Models.Device", "Device")
                        .WithMany("DeviceParameters")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("DataManagement.Models.Diode", b =>
                {
                    b.HasOne("DataManagement.Models.Device", "Device")
                        .WithOne()
                        .HasForeignKey("DataManagement.Models.Diode", "DiodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("DataManagement.Models.Lab", b =>
                {
                    b.HasOne("DataManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("LabLeaderId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DataManagement.Models.LabEquipment", b =>
                {
                    b.HasOne("DataManagement.Models.Equipment", "Equipment")
                        .WithMany("LabEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataManagement.Models.Lab", "Lab")
                        .WithMany("LabEquipments")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("DataManagement.Models.LabProject", b =>
                {
                    b.HasOne("DataManagement.Models.Lab", "Lab")
                        .WithMany("LabProjects")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataManagement.Models.Project", "Project")
                        .WithMany("LabProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lab");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DataManagement.Models.Measurement", b =>
                {
                    b.HasOne("DataManagement.Models.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataManagement.Models.Equipment", null)
                        .WithMany("Measurements")
                        .HasForeignKey("EquipmentId");

                    b.HasOne("DataManagement.Models.Sample", null)
                        .WithMany()
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DataManagement.Models.Resistor", b =>
                {
                    b.HasOne("DataManagement.Models.Device", "Device")
                        .WithOne()
                        .HasForeignKey("DataManagement.Models.Resistor", "ResistorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataManagement.Models.Tlm", "Tlm")
                        .WithMany("Resistors")
                        .HasForeignKey("TlmId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");

                    b.Navigation("Tlm");
                });

            modelBuilder.Entity("DataManagement.Models.RolePermission", b =>
                {
                    b.HasOne("DataManagement.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataManagement.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DataManagement.Models.Sample", b =>
                {
                    b.HasOne("DataManagement.Models.Batch", "Batch")
                        .WithMany("Samples")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("DataManagement.Models.Transistor", b =>
                {
                    b.HasOne("DataManagement.Models.Device", "Device")
                        .WithOne()
                        .HasForeignKey("DataManagement.Models.Transistor", "TransistorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("DataManagement.Models.UserLab", b =>
                {
                    b.HasOne("DataManagement.Models.Lab", "Lab")
                        .WithMany("UserLabs")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataManagement.Models.User", "User")
                        .WithMany("UserLabs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lab");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataManagement.Models.UserProject", b =>
                {
                    b.HasOne("DataManagement.Models.Project", "Project")
                        .WithMany("UserProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataManagement.Models.User", "User")
                        .WithMany("UserProjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataManagement.Models.UserRole", b =>
                {
                    b.HasOne("DataManagement.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataManagement.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataManagement.Models.Batch", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("DataManagement.Models.Device", b =>
                {
                    b.Navigation("DeviceParameters");
                });

            modelBuilder.Entity("DataManagement.Models.Equipment", b =>
                {
                    b.Navigation("LabEquipments");

                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("DataManagement.Models.Lab", b =>
                {
                    b.Navigation("LabEquipments");

                    b.Navigation("LabProjects");

                    b.Navigation("UserLabs");
                });

            modelBuilder.Entity("DataManagement.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("DataManagement.Models.Project", b =>
                {
                    b.Navigation("LabProjects");

                    b.Navigation("UserProjects");
                });

            modelBuilder.Entity("DataManagement.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DataManagement.Models.Sample", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("DataManagement.Models.Tlm", b =>
                {
                    b.Navigation("Resistors");
                });

            modelBuilder.Entity("DataManagement.Models.User", b =>
                {
                    b.Navigation("UserLabs");

                    b.Navigation("UserProjects");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
